kind = "web"
previewPath = "/"
title = "NexaTech - Formation Programmation"
version = "1.0.0"
id = "artifacts/nexatech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25342

[services.development]
run = "pnpm --filter @workspace/nexatech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexatech", "run", "build" ]
publicDir = "artifacts/nexatech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25342"
BASE_PATH = "/"
